/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.abring.fetchremotes.gui;

import java.awt.event.KeyEvent;
import org.json.JSONArray;

/**
 *
 * @author Karima
 */
public class Edit extends javax.swing.JDialog {

    private JSONArray array;
             
    /**
     * Creates new form Edit
     * @param parent
     * @param modal
     * @param array
     */
    public Edit(java.awt.Frame parent, boolean modal, JSONArray array) {
        super(parent, modal);
        initComponents();
        this.array = array;
        this.jTxtValue.setText(String.valueOf(array.get(0)));
        this.jTxtBits.setText(String.valueOf(array.get(1)));
        this.jTxtType.setText(String.valueOf(array.get(2)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblValue = new javax.swing.JLabel();
        jLblBits = new javax.swing.JLabel();
        jLblType = new javax.swing.JLabel();
        jTxtValue = new javax.swing.JTextField();
        jTxtBits = new javax.swing.JTextField();
        jTxtType = new javax.swing.JTextField();
        jBtnOk = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit");
        setMaximumSize(new java.awt.Dimension(2147483647, 133));
        setMinimumSize(new java.awt.Dimension(220, 133));
        setType(java.awt.Window.Type.UTILITY);

        jLblValue.setLabelFor(jTxtValue);
        jLblValue.setText("value");

        jLblBits.setLabelFor(jTxtBits);
        jLblBits.setText("bits");

        jLblType.setLabelFor(jTxtType);
        jLblType.setText("type");

        jTxtValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtValue.setNextFocusableComponent(jTxtBits);
        jTxtValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtValueFocusGained(evt);
            }
        });
        jTxtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtValueKeyPressed(evt);
            }
        });

        jTxtBits.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtBits.setNextFocusableComponent(jTxtType);
        jTxtBits.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtBitsFocusGained(evt);
            }
        });
        jTxtBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtBitsKeyPressed(evt);
            }
        });

        jTxtType.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtType.setNextFocusableComponent(jBtnOk);
        jTxtType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtTypeFocusGained(evt);
            }
        });
        jTxtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtTypeKeyPressed(evt);
            }
        });

        jBtnOk.setText("Ok");
        jBtnOk.setNextFocusableComponent(jBtnCancel);
        jBtnOk.setOpaque(false);
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });
        jBtnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnOkKeyPressed(evt);
            }
        });

        jBtnCancel.setText("Cancel");
        jBtnCancel.setNextFocusableComponent(jTxtValue);
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        jBtnCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnCancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblValue, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLblBits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtValue)
                            .addComponent(jTxtBits)
                            .addComponent(jTxtType)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 148, Short.MAX_VALUE)
                        .addComponent(jBtnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblValue)
                    .addComponent(jTxtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBits)
                    .addComponent(jTxtBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblType)
                    .addComponent(jTxtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.array = null;
        this.dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        this.array.put(0, Long.parseLong(this.jTxtValue.getText()));
        this.array.put(1, Long.parseLong(this.jTxtBits.getText()));
        this.array.put(2, Long.parseLong(this.jTxtType.getText()));
        this.dispose();
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jTxtValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtValueFocusGained
        this.jTxtValue.select(0, this.jTxtValue.getText().length());
    }//GEN-LAST:event_jTxtValueFocusGained

    private void jTxtBitsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtBitsFocusGained
        this.jTxtBits.select(0, this.jTxtBits.getText().length());
    }//GEN-LAST:event_jTxtBitsFocusGained

    private void jTxtTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTypeFocusGained
        this.jTxtType.select(0, this.jTxtType.getText().length());
    }//GEN-LAST:event_jTxtTypeFocusGained

    private void jTxtValueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtValueKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jTxtBits.requestFocus();
        }
    }//GEN-LAST:event_jTxtValueKeyPressed

    private void jTxtBitsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBitsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jTxtType.requestFocus();
        }
    }//GEN-LAST:event_jTxtBitsKeyPressed

    private void jTxtTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTypeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jBtnOk.requestFocus();
        }
    }//GEN-LAST:event_jTxtTypeKeyPressed

    private void jBtnOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnOkKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.array.put(0, Long.parseLong(this.jTxtValue.getText()));
            this.array.put(1, Long.parseLong(this.jTxtBits.getText()));
            this.array.put(2, Long.parseLong(this.jTxtType.getText()));
            this.dispose();
        }
    }//GEN-LAST:event_jBtnOkKeyPressed

    private void jBtnCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnCancelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.array = null;
            this.dispose();
        }
    }//GEN-LAST:event_jBtnCancelKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JLabel jLblBits;
    private javax.swing.JLabel jLblType;
    private javax.swing.JLabel jLblValue;
    private javax.swing.JTextField jTxtBits;
    private javax.swing.JTextField jTxtType;
    private javax.swing.JTextField jTxtValue;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the array
     */
    public JSONArray getJSONArray() {
        return array;
    }
}
